### ISSUE TITLE
Support WireHole / wireguard docker

### ISSUE THREAD

**Issue by RangerRU** [FlyveHest/wg-friendly-peer-names#6]
How can I use in WireHole ?

Thanks in advance!

**Comment by dmdmdm** [comment]
Its just one file so.  Download it and place in /usr/local/bin and make it executable `chmod +a wgg`

**Comment by FlyveHest** [comment]
I haven't used Wirehole, but it looks like it runs WireGuard in its own container, using the linuxserver/wireguard image.

You would need to add `wgg.sh` to the wireguard image either by creating your own image, adding it and the use that in the composer file, or copying it into your local container after it has been instantiated (this needs to be done every time its updated, though)

You can then run the script from your host machine by doing something like

`docker exec -it wireguard wgg.sh`

I actually do something like this in my own container wireguard docker setup.

**Comment by RangerRU** [comment]
Thank you very much everyone!

Used the article https://adamtheautomator.com/docker-cp/
