### ISSUE TITLE
line 60: script: command not found

### ISSUE THREAD

**Issue by RangerRU** [FlyveHest/wg-friendly-peer-names#7]
On the actual version of wireguard (docker-compose), the script gives an error:

`wgg.sh: line 60: script: command not found`

**Comment by FlyveHest** [comment]
Best guess is that the docker image doesn't contain the `script` command, which would cause wgg.sh to fail.

I'm guessing you are using the linuxserver.io docker image?  If so, you can see if you can probably roll your own docker image based on it, and add the util-linux package.

**Comment by RangerRU** [comment]
from Discord (https://discord.com/channels/354974912613449730/1107169857771946095/1107217961225293876):

> recently linuxserver switched wireguard to be based on alpine. I guess that this doesn't include the command anymore. you can use https://github.com/linuxserver/docker-mods/tree/universal-package-install to install additional packages though.
> 
> If you need further assistance, please use ⁠other-support because this script isn't part of the linuxserver container and linuxserver won't provide support for it. We still may be able to help in ⁠other-support

**Comment by RangerRU** [comment]
fix:

```
docker exec -it wireguard /bin/bash
apk add util-linux
apk add ncurses
exit
```
